#!/usr/bin/env python3
"""
Generate everything Android needs per widget provider from widgets/Catalog.kt:

  res/xml/widget_<id>.xml       appwidget-provider (reconfigurable|configuration_optional, configure activity,
                                home screen + keyguard so Samsung's cover screen lists it)
  res/layout/preview_<id>.xml   previewLayout pointing at drawable-nodpi/preview_<id>.png
  res/values/widgets.xml        labels (w_<id>) and descriptions (d_<id>)
  AndroidManifest.xml           the <receiver> block between the WIDGETS markers

    python3 tools/gen_widgets.py

Preview PNGs come from the app itself (MainActivity dump) or the devkit renderer.
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(ROOT, "app/src/main")
CATALOG = os.path.join(APP, "kotlin/in_/weenja/hawidgets/widgets/Catalog.kt")
KINDS = os.path.join(ROOT, "shared/src/commonMain/kotlin/in_/weenja/hawidgets/core/Kinds.kt")

# descriptions of the widgets that are not a shared kind (or need their own words)
DESC = {
    "weather_s": "Temperature and condition in a square tile.",
    "now": "The floating capsule: artwork, title, ‹ ▶ ›. Make it taller for the full player.",
    "now_bar": "Full player: artwork, progress, ‹ ▶ ›, volume.",
    "now_s": "Artwork, title and play / pause in a square tile.",
    "t_bulb": "Any entity as a 1x1 or 2x1 tile. Tap = toggle, open, lock or run.",
    "body": "Body battery, steps, sleep, resting heart rate and stress (Garmin Connect).",
    "body_s": "Body battery ring in a square tile.",
    "mac": "Mac app tiles, wake, sleep, lock, screen off, screenshot, keep awake.",
    "macscreen": "The last screenshot of the Mac. Tap to take a new one.",
    "claude": "Claude Code sessions, hosts with open / new / stop, mode picker, Start host.",
    "claude_s": "Live Claude Code sessions and Start host in a square tile.",
    "projects": "Project folders with git state; tap one to pick it for Claude Code.",
    "gaming": "Wake the gaming PC, pick a game, launch it.",
    "spend": "This month by category, insight, renewals, card dues and recent transactions.",
    "dues": "Predicted renewals and credit-card dues.",
    "budget": "Budget used, left per day, today and the last 7 days.",
    "budget_s": "Budget ring in a square tile.",
    "nutrition": "Calories, macros and water with quick-add chips.",
    "screentime": "Screen time today across phone, computer, PC and TV.",
    "screentime_s": "Screen time ring in a square tile.",
    "overhead": "Planes within 100 km and satellites above you, with the ISS pass.",
    "overhead_s": "Plane and satellite counts in a square tile.",
    "t_claude": "Start a Claude Code host in the selected folder.",
    "t_pc": "Wake-on-LAN for the gaming PC.",
    "t_lock": "Lock the Mac.",
    "t_water": "Log a glass of water.",
    "t_screenoff": "Turn the Mac display off.",
    "tube": "A second light: toggle, brightness, colour temperature.",
    "t_tube": "One-tap toggle for a second light.",
    "t_fan": "One-tap fan toggle.",
    "t_tv": "One-tap TV power.",
    "t_movie": "Run your movie-mode script.",
    "t_alloff": "Switch off lights, TV and music.",
    "t_music": "Play / pause the music player.",
}

def cells(eid, w, h):
    """(minWidth, minHeight, targetCellWidth, targetCellHeight) in dp."""
    if w < 100 and h < 100: return 40, 40, 1, 1
    if w < 200 and h < 100: return 110, 40, 2, 1
    if w < 200: return 110, 110, 2, 2
    if h < 100: return 250, 40, 4, 1
    if h >= 300: return 250, 250, 4, 3
    return 250, 110, 4, 2

def main():
    src = open(CATALOG, encoding="utf-8").read()
    rows = re.findall(r'(core|extra|legacy)\("([a-z0-9_]+)", (\w+)::class\.java, "([a-z_]+)", "([^"]+)", ([\d.]+)f, ([\d.]+)f', src)
    kinds = dict(re.findall(r'KindSpec\("([a-z_]+)", "[^"]*", "([^"]+)"', open(KINDS, encoding="utf-8").read()))
    labels = []; receivers = []
    for group, eid, cls, kind, title, w, h in rows:
        w = float(w); h = float(h)
        desc = DESC.get(eid) or kinds.get(kind) or title
        label = title if title.startswith("Tile") else "Homebase · " + title
        labels.append((eid, label, desc))
        mw, mh, cw, ch = cells(eid, w, h)
        with open(os.path.join(APP, "res/xml/widget_%s.xml" % eid), "w") as f:
            f.write('''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/gen_widgets.py -->
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:minWidth="%ddp"
    android:minHeight="%ddp"
    android:minResizeWidth="40dp"
    android:minResizeHeight="40dp"
    android:targetCellWidth="%d"
    android:targetCellHeight="%d"
    android:maxResizeWidth="600dp"
    android:maxResizeHeight="700dp"
    android:updatePeriodMillis="1800000"
    android:initialLayout="@layout/widget_frame"
    android:initialKeyguardLayout="@layout/widget_frame"
    android:previewLayout="@layout/preview_%s"
    android:previewImage="@drawable/preview_%s"
    android:description="@string/d_%s"
    android:resizeMode="horizontal|vertical"
    android:widgetCategory="home_screen|keyguard"
    android:configure="in_.weenja.hawidgets.ConfigureActivity"
    android:widgetFeatures="reconfigurable|configuration_optional" />
''' % (mw, mh, cw, ch, eid, eid, eid))
        with open(os.path.join(APP, "res/layout/preview_%s.xml" % eid), "w") as f:
            f.write('''<?xml version="1.0" encoding="utf-8"?>
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="fitCenter"
    android:adjustViewBounds="true"
    android:src="@drawable/preview_%s"
    android:contentDescription="@string/w_%s" />
''' % (eid, eid))
        receivers.append('''        <receiver
            android:name=".widgets.%s"
            android:exported="true"
            android:label="@string/w_%s">
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
            </intent-filter>
            <meta-data
                android:name="android.appwidget.provider"
                android:resource="@xml/widget_%s" />
            <meta-data
                android:name="com.samsung.android.appwidget.provider"
                android:resource="@xml/samsung_cover" />
        </receiver>
''' % (cls, eid, eid))
    esc = lambda s: s.replace("&", "&amp;").replace("'", "\\'").replace("<", "&lt;")
    with open(os.path.join(APP, "res/values/widgets.xml"), "w") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/gen_widgets.py -->\n<resources>\n')
        for eid, label, desc in labels:
            f.write('    <string name="w_%s">%s</string>\n    <string name="d_%s">%s</string>\n' % (eid, esc(label), eid, esc(desc)))
        f.write('</resources>\n')
    man = os.path.join(APP, "AndroidManifest.xml")
    m = open(man, encoding="utf-8").read()
    a = m.index("        <!-- WIDGETS -->"); b = m.index("        <!-- /WIDGETS -->")
    m = m[:a] + "        <!-- WIDGETS -->\n" + "".join(receivers) + m[b:]
    open(man, "w", encoding="utf-8").write(m)
    # drop provider files of ids that no longer exist
    ids = {r[1] for r in rows}
    for d, pre in (("res/xml", "widget_"), ("res/layout", "preview_"), ("res/drawable-nodpi", "preview_")):
        for fn in os.listdir(os.path.join(APP, d)):
            if fn.startswith(pre):
                eid = fn[len(pre):].rsplit(".", 1)[0]
                if eid not in ids: os.remove(os.path.join(APP, d, fn)); print("removed", d, fn)
    print("%d providers" % len(rows))

if __name__ == "__main__":
    main()
