#!/usr/bin/env python3
"""
Generate Material Design Icons vector drawables + the Icons.kt lookup table.

    npm pack @mdi/js && tar xzf mdi-js-*.tgz        # gives package/mdi.js
    python3 tools/gen_icons.py package/mdi.js

Icons are picked from: every drawable already in res/drawable (ic_*.xml), every icon key the shared
rules return (quoted mdi names in shared/.../core/*.kt) and EXTRA below. Existing files are left alone.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "app/src/main/res/drawable")
CORE = os.path.join(ROOT, "shared/src/commonMain/kotlin/in_/weenja/hawidgets/core")
OUT = os.path.join(ROOT, "app/src/main/kotlin/in_/weenja/hawidgets/ui/Icons.kt")

EXTRA = """
refresh cog pencil plus magnify check close home-assistant star star-outline auto-fix backup-restore download upload wifi
qrcode-scan content-copy puzzle chevron-down chevron-up chevron-left chevron-right solar-power transmission-tower home-battery
home-lightning-bolt battery-charging ev-station car-electric map-marker-distance trash-can recycle calendar-clock washing-machine
dishwasher tumble-dryer timer-sand shield-check shield-alert alert-circle account-circle home-map-marker chart-line clock-outline
stop play pause arrow-up arrow-down home-floor-0 home-floor-1 texture-box devices help-circle-outline home-outline gauge
lightning-bolt-circle battery-charging-60 flash-outline sofa bed desk stove shower tree garage-variant office-building
format-list-bulleted view-dashboard-outline lan-connect server-network link-variant-off eye-off delete-outline drag
information-outline arrow-right-circle play-pause skip-next skip-previous home-thermometer thermometer-chevron-up
thermometer-chevron-down plus-circle minus-circle fire snowflake sync alert-circle-outline check-circle map-marker
""".split()

# words from the Kotlin sources that happen to be icon names but are not used as icons
SKIP = set("domain graph grid latitude longitude message null radius safe script select security switch tag update card cards key remote".split())

def pascal(name):
    return "mdi" + "".join(p[:1].upper() + p[1:] for p in name.split("-"))

def main(mdi_js):
    src = open(mdi_js, encoding="utf-8").read()
    paths = dict(re.findall(r'export var (mdi\w+) = "([^"]+)"', src))
    have = {f[3:-4].replace("_", "-") for f in os.listdir(RES) if f.startswith("ic_") and f.endswith(".xml")
            and not f.startswith("ic_launcher")}
    wanted = set(EXTRA)
    for f in os.listdir(CORE):
        if f.endswith(".kt"):
            for m in re.findall(r'"([a-z][a-z0-9]*(?:-[a-z0-9]+)+|[a-z]{3,})"', open(os.path.join(CORE, f), encoding="utf-8").read()):
                if pascal(m) in paths and m not in SKIP:
                    wanted.add(m)
    made = []
    for name in sorted(wanted - have):
        key = pascal(name)
        if key not in paths:
            print("missing in mdi:", name); continue
        fn = os.path.join(RES, "ic_" + name.replace("-", "_") + ".xml")
        with open(fn, "w") as fh:
            fh.write('<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
                     '    android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">\n'
                     '    <path android:fillColor="#FFFFFFFF" android:pathData="%s"/>\n</vector>\n' % paths[key])
        made.append(name)
    allnames = sorted(have | set(made))
    with open(OUT, "w") as fh:
        fh.write("package in_.weenja.hawidgets.ui\n\n")
        fh.write("import in_.weenja.hawidgets.R\n\n")
        fh.write("// Generated by tools/gen_icons.py. Do not edit.\n\n")
        fh.write("/** Material Design Icons by mdi name (\"lightbulb-on\"), as used by the shared rules. */\n")
        fh.write("object Icons {\n    private val map: Map<String, Int> = hashMapOf(\n")
        for n in allnames:
            fh.write('        "%s" to R.drawable.ic_%s,\n' % (n, n.replace("-", "_")))
        fh.write("    )\n\n")
        fh.write("    /** Drawable for an mdi name (with or without the \"mdi:\" prefix), else [fallback]. */\n")
        fh.write("    fun of(name: String?, fallback: Int = R.drawable.ic_circle_medium): Int = name?.removePrefix(\"mdi:\")?.let { map[it] } ?: fallback\n\n")
        fh.write("    fun has(name: String?): Boolean = name?.removePrefix(\"mdi:\")?.let { map.containsKey(it) } == true\n}\n")
    print("generated %d new icons, %d total" % (len(made), len(allnames)))

if __name__ == "__main__":
    main(sys.argv[1])
